### PR TITLE
APP-6365 update security-policy-templates with mapped controls

### PR DESCRIPTION
**Pull request by byricketts**

### CODE REVIEW

**Comment by erkangz** [comment]
I assume these are done via a script so I don't need to double check on all the mappings?

**Comment by byricketts** [comment]
> I assume these are done via a script so I don't need to double check on all the mappings?

Yes, a script was used to generate the `mappedControls` property for each standard. Unfortunately, the script was unable to preserve object-key order, so some manual stitching was required after-the-fact to prevent this PR diff from burgeoning.

**Comment by erkangz** [comment]
Is they ready? It has no reviewer on the PR yet. Happy to approve once it's ready

**Comment by henrymgarrett** [comment]
HUGE thank you @byricketts .  Were you able to import these into the app?

**Comment by byricketts** [comment]
> HUGE thank you @byricketts . Were you able to import these into the app?

I'll manually deploy to verify.

**Comment by henrymgarrett** [comment]
> 

No need, you can just use the import by JSON functionality and copy/paste your JSON

**Review by henrymgarrett — APPROVED** [review]

**Pull request merged**
